robotronics/models.py
from django.db import models
import datetime

class Member(models.Model):
    Coord16 = 'Coord16'
    Coord = 'Coord'
    Team = 'Team'
    Team16 = 'Team16'
    Webdev = 'Webdev'
    CHOICES = ((Coord16, 'Coord16'), (Coord, 'Coord'), (Team, 'Team'), (Team16, 'Team16'), (Webdev, 'Webdev'))
    role = models.CharField(max_length=20, choices=CHOICES, default=Team)
    name = models.CharField(max_length=200)
    facebook = models.CharField(max_length=500, null=True)
    linkedin = models.CharField(max_length=500, null=True)
    github = models.CharField(max_length=500, null=True)
    details = models.CharField(max_length=500, null=True)

    def __str__(self):
        return self.role + ' - ' + self.name

class Project(models.Model):
    Title = models.CharField(max_length=200)
    text = models.TextField()
    date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.Title

    def desc(self):
        return self.text[:75]

class Tutorial(models.Model):
    Title = models.CharField(max_length=200)
    text = models.TextField()
    date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.Title

    def desc(self):
        return self.text[:75]

robotronics/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

robotronics/views.py
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render, redirect

from .models import Member, Project, Tutorial

def index(request):
    return render(request, 'robotronics/index.html')

def about(request):
    return render(request, 'robotronics/about.html')

def team(request):
    coord16 = Member.objects.filter(role='Coord16')
    coord = Member.objects.filter(role='Coord')
    team = Member.objects.filter(role='Team')
    team16 = Member.objects.filter(role='Team16')
    webdev = Member.objects.filter(role='Webdev')
    Member.link = property(lambda self: ''.join(self.name.split()))
    return render(request, 'robotronics/team.html', {
        'coord16': coord16,
        'coord': coord,
        'team': team,
        'team16': team16,
        'webdev': webdev,
    })

def tutorial(request):
    list_tutorials = Tutorial.objects.all()
    return render(request, 'robotronics/tutorial.html', {'list_tutorials': list_tutorials})

def project(request):
    list_projects = Project.objects.all()
    return render(request, 'robotronics/project.html', {'list_projects': list_projects})

def proj(request, project_id):
    proj = get_object_or_404(Project, id=project_id)
    previousp = Project.objects.filter(id__lt=project_id).last()
    nextp = Project.objects.filter(id__gt=project_id).first()
    return render(request, 'robotronics/postP.html', {'proj': proj, 'previousp': previousp, 'nextp': nextp})

def tut(request, tutorial_id):
    tut = get_object_or_404(Tutorial, id=tutorial_id)
    previousp = Tutorial.objects.filter(id__lt=tutorial_id).last()
    nextp = Tutorial.objects.filter(id__gt=tutorial_id).first()
    return render(request, 'robotronics/postT.html', {'tut': tut, 'previousp': previousp, 'nextp': nextp})

def send_mail(request):
    subject = request.POST.get('subject', '')
    message = request.POST.get('message', '')
    from_email = request.POST.get('from_email', '')
    if subject and message and from_email:
        try:
            send_mail(subject, message, from_email, ['varunjustrocks@gmail.com'])
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return HttpResponseRedirect('/contact/thanks/')
    else:
        return HttpResponse('Make sure all fields are entered and valid.')

robotronics/templates/robotronics/about.html
<!-- About Page -->
{% extends 'robotronics/base.html' %}

{% block navbar %}
  <li><a href="{% url 'contacts' %}">Contact Us</a></li>
  <li><a href="http://sntc.iitmandi.ac.in/inv_man">Resources</a></li>
  <li><a href="{% url 'team' %}">Team</a></li>
  <li><a href="{% url 'tutorial' %}">Tutorials</a></li>
  <li><a href="{% url 'project' %}">Projects</a></li>
  <li class="active"><a href="{% url 'about' %}">About Us</a></li>
  <li><a href="{% url 'index' %}" class="scroll">Home</a></li>
{% endblock %}

{% block banner %}
  <h1>ROBOTRONICS CLUB</h1>
  <div class="clearfix"></div>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="jumbotron xnew">
      <h2>About Us</h2>
    </div>
    <div class="jumbotron xnew">
      <h2>Who are we?</h2>
    </div>
    <div>
      <p class="text">Robotronics Club is the official club under Science and Technology Council, IIT Mandi. It is one of the most active clubs created to bring out the creativity among the students and make them familiar with the ever growing world of Robotics. The club provides an entry point and a platform to the students where they can come and learn this amazing field of technology.</p>
    </div>
    <div class="jumbotron xnew">
      <h2>What do we do?</h2>
    </div>
    <div>
      <p class="text">The club organises activities throughout the year and aids and encourage the students to convert their ideas into reality and build robots beneficial for the whole mankind.
        It is the main focal point for activities related Robotronics.
      </p>
    </div>
    <div>
      <p class="text">So, come and “Let’s automate the boring stuff..”
      </p>
    </div><br><br>
  </div>
{% endblock %}

robotronics/templates/robotronics/base.html
<!-- Base template for other pages -->
<!DOCTYPE html>
<html lang="en">
	{% load static %}
	<head>
		<title>Robotronics Club - IIT Mandi</title>
		<!-- favicon -->
		<link rel="icon" type="image/x-icon" href="{% static 'robotronics/images/robo-fav.ico' %}">
		<!-- /favicon -->
		<link href="{% static 'robotronics/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="{% static 'robotronics/js/jquery.min.js' %}"></script>
		<!-- Custom Theme files -->
		<!-- animated-css -->
		<link href="{% static 'robotronics/css/animate.css' %}" rel="stylesheet" type="text/css" media="all">
		<link href="{% static 'robotronics/fontello-2bd2532a/css/fontello.css' %}" rel="stylesheet" type="text/css" media="all">
		<script src="{% static 'robotronics/js/wow.min.js' %}"></script>
		<script>
			new WOW().init();
		</script>
		<!-- animated-css -->
		<link href="{% static 'robotronics/css/style.css' %}" rel='stylesheet' type='text/css' />
		<!-- Custom Theme files -->
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script type="application/x-javascript">
			addEventListener("load", function() {
				setTimeout(hideURLbar, 0);
			}, false);
			function hideURLbar() {
				window.scrollTo(0, 1);
			}
		</script>
		</script>
		<!-- webfonts -->
		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
		<!--//webfonts -->
	</head>
	<body>
		<div class="bgbase">
			<div class="bg-tint">
				<!-- start-header -->
				<div id="home" class="header wow" data-wow-delay="0.4s">
					<div class="top-header">
						<div class="logo wow" data-wow-delay="0.4s">
							<a href="{% url 'index' %}"><img style="max-width: 250px;" src="{% static 'robotronics/images/robologo.png' %}" title="Robotronics Club" /></a>
						</div>
						<nav class="top-nav wow" data-wow-delay="0.4s">
							<span class="menu">
								<ul class="top-nav">
						<!-- start-top-nav -->
									{% block navbar %}
										<li><a href="{% url 'contacts' %}">Contact Us</a></li>
										<li><a href="http://sntc.iitmandi.ac.in/inv_man">Resources</a></li>
										<li><a href="{% url 'team' %}">Team</a></li>
										<li><a href="{% url 'tutorial' %}">Tutorials</a></li>
										<li><a href="{% url 'project' %}">Projects</a></li>
										<li><a href="{% url 'about' %}">About Us</a></li>
										<li class="active"><a href="{% url 'index' %}" class="scroll">Home</a></li>
									{% endblock %}
								</ul>
							</span>
						</nav>
						<script>
							$("span.menu").click(function() {
								$(".top-nav ul").slideToggle(200);
							});
						</script>
						<div class="clearfix"> </div>
					</div>
				</div>
				<!-- banner -->
				<div class="banner text-right">
					<div class="container">

					</div>
				</div>
				<!-- banner -->
			</div>
		</div>
		<!-- //End-header-->
		{% block content %}
		{% endblock %}
		<!-- footer -->
		<div class="footer">
			<div class="container">
				<div class="footer-grids">
					<div class="col-md-3 footer-grid ftr-sec">
						<h3>Navigation</h3>
						<ul>
							<li><a href="{% url 'index' %}">Home</a></li>
							<li><a href="{% url 'about' %}">About Us</a></li>
							<li><a href="{% url 'project' %}">Projects</a></li>
							<li><a href="{% url 'tutorial' %}">Tutorials</a></li>
							<li><a href="{% url 'team' %}">Team</a></li>
							<li><a href="http://sntc.iitmandi.ac.in/inv_man">Resources</a></li>
						</ul>
					</div>
					<div class="clearfix"></div>
					<div class="span10 offset1">
						<div class="social-icons">
							<ul>
								<li><a href="https://www.facebook.com/groups/robotronix.iit.mandi/"><i class="icon-facebook"></i></a></li>
								<li><a href="https://www.youtube.com/channel/UCRWNmRmnbqJpWU9ICXQZ-Tg"><i class="icon-youtube-play"></i></a></li>
								<li><a href="https://github.com/RobotronicsClubIITMandi"><i class="icon-github-circled"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<footer class="footer-bottom">
			<div style="text-align: center;">
				<span style="color: grey;">
					Developed by:
					<a style="color: grey;" href="https://www.facebook.com/akshatmatrix">Akshat Malviya</a>, <!-- :D -->
					<a style="color: grey;" href="https://www.facebook.com/varunsingh110">Varun Singh</a>,
					<a style="color: grey;" href="https://www.facebook.com/rishis8">Rishi Sharma</a>,
					<a style="color: grey;" href="https://www.facebook.com/vsvipul555">Vipul Sharma</a>.
					Initiated by:
					<a style="color: grey;" href="https://www.facebook.com/virendrasingh.suryavanshi.1">Suryavanshi Virendrasingh</a>
				</span>
				<br>
				<span style="color: grey;">
					&copy; Robotronics Club - <a style="color: grey;" href="https://www.iitmandi.ac.in/">IIT Mandi</a>. All Rights Reserved.
				</span>
			</div>
		</footer>
		<!-- footer -->
	</body>
</html>

robotronics/templates/robotronics/contacts.html
<!-- Contactus Page -->
{% extends 'robotronics/base.html' %}

{% block navbar %}
  <li class="active"><a href="{% url 'contacts' %}">Contact Us</a></li>
  <li><a href="http://sntc.iitmandi.ac.in/inv_man">Resources</a></li>
  <li><a href="{% url 'team' %}">Team</a></li>
  <li><a href="{% url 'tutorial' %}">Tutorials</a></li>
  <li><a href="{% url 'project' %}">Projects</a></li>
  <li><a href="{% url 'about' %}">About Us</a></li>
  <li><a href="{% url 'index' %}" class="scroll">Home</a></li>
{% endblock %}

{% block content %}
  <div class="container-fluid">
      <div class="mapdiv">
          <div class="panel panel-default">
              <div class="text-center headera">Location</div>
              <div class="panel-body text-center">
                  <div id="map1" class="map">
                  </div>
              </div>
          </div>
      </div>
  </div>
  <div class="container">
      <div class="row contactrow">
              <div class="well well-sm">
                  <form class="form-horizontal" method="post">
                    {% csrf_token %}
                      <fieldset>
                          <legend class="text-center headera">Contact us</legend>
                          <div class="form-group">
                              <div class="col-md-10 col-md-offset-1">
                                  <input type="text" name="first" id="id_first" placeholder="First Name" class="form-control" required/>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-md-10 col-md-offset-1">
                                  <input type="text" name="last" id="id_last" placeholder="Last Name" class="form-control" required/>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-md-10 col-md-offset-1">
                                  <input id="id_from_email" name="from_email" type="email" placeholder="Email" class="form-control" required/>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-md-10 col-md-offset-1">
                                  <textarea name="message" id="id_message" required cols="40" rows="10" placeholder="Message" class="form-control"></textarea>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-md-12 text-center">
                                  <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                              </div>
                          </div>
                      </fieldset>
                  </form>
          </div>
      </div>
  </div>

  <script src="https://maps.google.com/maps/api/js?key=AIzaSyAM_lDKrlaozbPeVilL2dhJGa7bBBgrBOU"></script>

  <script type="text/javascript">
      jQuery(function ($) {
          function init_map1() {
              var myLocation = new google.maps.LatLng(31.7754, 76.9861);
              var mapOptions = {
                  center: myLocation,
                  zoom: 16
              };
              var marker = new google.maps.Marker({
                  position: myLocation,
                  title: "Property Location"
              });
              var map = new google.maps.Map(document.getElementById("map1"),
                  mapOptions);
              marker.setMap(map);
          }
          init_map1();
      });
  </script>
{% endblock %}

robotronics/templates/robotronics/index.html
<!-- Home Page -->
<!DOCTYPE html>
<html lang="en">
	{% load static %}
	<head>
		<title>Robotronics Club - IIT Mandi</title>
		<link href="{% static 'robotronics/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="{% static 'robotronics/js/jquery.min.js' %}"></script>
		<!-- Custom Theme files -->
		<!-- animated-css -->
		<link href="{% static 'robotronics/css/animate.css' %}" rel="stylesheet" type="text/css" media="all">
		<link href="{% static 'robotronics/fontello-2bd2532a/css/fontello.css' %}" rel="stylesheet" type="text/css" media="all">
		<script src="{% static 'robotronics/js/wow.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'robotronics/js/preloader.js' %}"></script>
		<script>
			new WOW().init();
		</script>
		<!-- animated-css -->
		<link href="{% static 'robotronics/css/style.css' %}" rel='stylesheet' type='text/css' />
		<!-- Custom Theme files -->
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script type="application/x-javascript">
			addEventListener("load", function() {
				setTimeout(hideURLbar, 0);
			}, false);
			function hideURLbar() {
				window.scrollTo(0, 1);
			}
		</script>
		</script>
		<!-- webfonts -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800" rel="stylesheet" type="text/css">
		<!-- <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> -->
		<!-- <link href='https://fonts.googleapis.com/css?family=Muli:400,300,600,700,800' rel='stylesheet' type='text/css'> -->
		<link rel="icon" type="image/x-icon" href="{% static 'robotronics/images/robo-fav.ico' %}">
		<!--//webfonts -->
	</head>
	<body onload="uptownfunc()" style="margin: 0;">
		<div id="preloader-wrapper">
			<div id="preloader">
				<div id="preloader-img"></div>
				<br>
				<div id="preloader-text">
					&nbsp;<span id="motto"></span><span id="cursor"> </span>
				</div>
			</div>
		</div>
		<div id="theDiv" class="animate-bottom">

				<div class="crossfade">
				  <figure></figure>
				  <figure></figure>
				  <figure></figure>
				  <figure></figure>
				  <figure></figure>
				</div>
				<div class="bg-tint">
					<!-- start-header -->
					<div id="home" class="header wow" data-wow-delay="0.4s">
						<div class="top-header">
							<div class="logo wow" data-wow-delay="0.4s">
								<a href="{% url 'index' %}"><img style="max-width: 250px;" src="{% static 'robotronics/images/robologo.png' %}" title="Robotronics Club" /></a>
							</div>
							<nav class="top-nav wow" data-wow-delay="0.4s">
								<span class="menu">
									<ul class="top-nav">
							<!-- start-top-nav -->
										{% block navbar %}
											<li><a href="{% url 'contacts' %}">Contact Us</a></li>
											<li><a href="http://sntc.iitmandi.ac.in/inv_man">Resources</a></li>
											<li><a href="{% url 'team' %}">Team</a></li>
											<li><a href="{% url 'tutorial' %}">Tutorials</a></li>
											<li><a href="{% url 'project' %}">Projects</a></li>
											<li><a href="{% url 'about' %}">About Us</a></li>
											<li class="active"><a href="{% url 'index' %}" class="scroll">Home</a></li>
										{% endblock %}
									</ul>
								</span>
							</nav>
							<script>
								$("span.menu").click(function() {
									$(".top-nav ul").slideToggle(200);
								});
							</script>
							<div class="clearfix"> </div>
						</div>
					</div>
					<!-- banner -->
					<div class="banner text-right">
						<div class="container">
							<h1>ROBOTRONICS CLUB<br>IIT MANDI</h1>
							<div class="clearfix"></div>
							<p>Robotics + Electronics club of<br>Indian Institute of Technology, Mandi</p>
							<div class="clearfix"> </div>
						</div>
					</div>
					<!-- banner -->
				</div>


			<!-- footer -->
			<div class="footer">
				<div class="container">
					<div class="footer-grids">
						<div class="col-md-3 footer-grid ftr-sec wow fadeInLeft" data-wow-delay="0.4s">
							<h3>Navigation</h3>
							<ul>
								<li><a href="{% url 'index' %}">Home</a></li>
								<li><a href="{% url 'about' %}">About Us</a></li>
								<li><a href="{% url 'project' %}">Projects</a></li>
								<li><a href="{% url 'tutorial' %}">Tutorials</a></li>
								<li><a href="{% url 'team' %}">Team</a></li>
								<li><a href="http://sntc.iitmandi.ac.in/inv_man">Resources</a></li>
							</ul>
						</div>
						<div class="clearfix"></div>
						<div class="span10 offset1 wow fadeInUp" data-wow-delay = "0.4s">
							<div class="social-icons">
								<ul>
									<li><a href="https://www.facebook.com/groups/robotronix.iit.mandi/"><i class="icon-facebook"></i></a></li>
									<li><a href="https://www.youtube.com/channel/UCRWNmRmnbqJpWU9ICXQZ-Tg"><i class="icon-youtube-play"></i></a></li>
									<li><a href="https://github.com/RobotronicsClubIITMandi"><i class="icon-github-circled"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<footer class="footer-bottom">
				<div class="wow fadeInUp" data-wow-delay = "0.4s" style="text-align: center;">
					<span style="color: grey;">
						Developed by:
						<a style="color: grey;" href="https://www.facebook.com/akshatmatrix">Akshat Malviya</a>, <!-- :D -->
						<a style="color: grey;" href="https://www.facebook.com/varunsingh110">Varun Singh</a>,
						<a style="color: grey;" href="https://www.facebook.com/rishis8">Rishi Sharma</a>,
						<a style="color: grey;" href="https://www.facebook.com/vsvipul555">Vipul Sharma</a>.
						Initiated by:
						<a style="color: grey;" href="https://www.facebook.com/virendrasingh.suryavanshi.1">Suryavanshi Virendrasingh</a>
					</span>
					<br>
					<span style="color: grey;">&copy; Robotronics Club - <a style="color: grey;" href="https://www.iitmandi.ac.in/">IIT Mandi</a>. All Rights Reserved.</p></span>
				</footer>
				<!-- footer -->
			</div>
		</body>
	</html>

robotronics/templates/robotronics/postP.html
{% extends 'robotronics/base.html' %}

{% block navbar %}
  <li><a href="{% url 'index' %}" class="scroll">Home</a></li>
  <li><a href="{% url 'about' %}">About Us</a></li>
  <li class="active"><a href="{% url 'project' %}">Projects</a></li>
  <li><a href="{% url 'tutorial' %}">Tutorials</a></li>
  <li><a href="{% url 'team' %}">Team</a></li>
  <li><a href="http://sntc.iitmandi.ac.in/inv_man">Resources</a></li>
  <li><a href="{% url 'contacts' %}">Contact Us</a></li>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <hr>
      <h1 class="mt-4">{{ proj.Title }}</h1>
      <hr>
      <!-- Date/Time -->
      <p><b>Posted on {{ proj.date }}</b></p>
      <hr>
      <hr>
      <!-- Post Content -->
      {{ proj.text }}
      <hr>
      <ul class="pager col-lg-12">
        {% if previousp %}
          <li class="previous"><a href="{% url 'proj' previousp.id %}">&larr; Previous</a></li>
        {% endif %}
        {% if nextp %}
          <li class="next"><a href="{% url 'proj' nextp.id %}">Next &rarr;</a></li>
        {% endif %}
      </ul>
      <hr>

    </div>
  </div>
</div>
{% endblock %}

robotronics/templates/robotronics/postT.html
{% extends 'robotronics/base.html' %}

{% block navbar %}
  <li><a href="{% url 'index' %}" class="scroll">Home</a></li>
  <li><a href="{% url 'about' %}">About Us</a></li>
  <li><a href="{% url 'project' %}">Projects</a></li>
  <li class="active"><a href="{% url 'tutorial' %}">Tutorials</a></li>
  <li><a href="{% url 'team' %}">Team</a></li>
  <li><a href="http://sntc.iitmandi.ac.in/inv_man">Resources</a></li>
  <li><a href="{% url 'contacts' %}">Contact Us</a></li>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <hr>
      <h1 class="mt-4">{{ tut.Title }}</h1>
      <hr>
      <!-- Date/Time -->
      <p><b>Posted on {{ tut.date }}</b></p>
      <hr>
      <hr>
      <!-- Post Content -->
      {{ tut.text }}
      <hr>
      <ul class="pager col-lg-12">
        {% if previousp %}
          <li class="previous"><a href="{% url 'tut' previousp.id %}">&larr; Previous</a></li>
        {% endif %}
        {% if nextp %}
          <li class="next"><a href="{% url 'tut' nextp.id %}">Next &rarr;</a></li>
        {% endif %}
      </ul>
      <hr>

    </div>
  </div>
</div>
{% endblock %}

robotronics/templates/robotronics/project.html
<!-- About Page -->
{% extends 'robotronics/base.html' %}
{% load static %}

{% block navbar %}
  <li><a href="{% url 'contacts' %}">Contact Us</a></li>
  <li><a href="http://sntc.iitmandi.ac.in/inv_man">Resources</a></li>
  <li><a href="{% url 'team' %}">Team</a></li>
  <li><a href="{% url 'tutorial' %}">Tutorials</a></li>
  <li class="active"><a href="{% url 'project' %}">Projects</a></li>
  <li><a href="{% url 'about' %}">About Us</a></li>
  <li><a href="{% url 'index' %}" class="scroll">Home</a></li>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h2>Projects</h2>
    </div>
    <div class="row equal">
        <!-- Blog Post -->
        {% for proj in list_projects %}
          <div class="col-md-4 col-sm-4">
            <div class="card bg-light mb-4">
              <div class="card-body">
                <h2 class="card-title">{{ proj.Title }}</h2>
                <p class="card-text">{{ proj.desc }}...</p>
                <a href="{% url 'proj' proj.id %}" class="btn btn-primary">Read More &rarr;</a>
              </div>
              <div class="card-footer text-muted">
                Posted on {{ proj.date }}
              </div>
            </div>
          </div>
        {% endfor %}
    </div>
  </div>
{% endblock %}

robotronics/templates/robotronics/tutorial.html
<!-- Tutorials Page -->
{% extends 'robotronics/base.html' %}
{% block navbar %}
  <li><a href="{% url 'contacts' %}">Contact Us</a></li>
  <li><a href="http://sntc.iitmandi.ac.in/inv_man">Resources</a></li>
  <li><a href="{% url 'team' %}">Team</a></li>
  <li class="active"><a href="{% url 'tutorial' %}">Tutorials</a></li>
  <li><a href="{% url 'project' %}">Projects</a></li>
  <li><a href="{% url 'about' %}">About Us</a></li>
  <li><a href="{% url 'index' %}" class="scroll">Home</a></li>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h2>Tutorials</h2>
    </div>

    <div class="row">
      <!-- Blog Post -->
      {% for tut in list_tutorials %}
        <div class="col-md-4 col-sm-4">
          <div class="card mb-4">
            <div class="card-body">
              <h2 class="card-title">{{ tut.Title }}</h2>
              <p class="card-text">{{ tut.desc }}...</p>
              <a href="{% url 'tut' tut.id %}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              Posted on {{ tut.date }}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}